"""Frozen analysis helpers and fail-closed substrate adapters for Stage-S."""

from .analysis import (
    DECISION_CODES,
    compute_divergence_curve,
    compute_s1,
    compute_s2,
    compute_s3,
    compute_s4,
    compute_s5,
    decide_stage_s,
    evaluate_substrate,
    family_collapse_metrics,
    matched_time_tau,
    normalized_workspace_pose_rms,
)
from .calibration import (
    CALIBRATION_SCHEMA,
    make_calibration_record,
    select_calibration_setting,
)
from .integrity import (
    sha256_file,
    verify_completion_bundle,
    verify_completed_json,
    verify_sha256sums,
    write_completion,
    write_sha256sums,
)
from .robotwin import (
    AtomicFamilyWriter,
    CandidateRecord,
    CapabilityError,
    ExactReplayVerifier,
    ConcreteRoboTwinRuntime,
    EvoProxyStateAdapter,
    FamilyRolloutRunner,
    RoboTwinPins,
    select_published_tasks,
)

__all__ = [
    "AtomicFamilyWriter",
    "CALIBRATION_SCHEMA",
    "CandidateRecord",
    "CapabilityError",
    "DECISION_CODES",
    "ExactReplayVerifier",
    "ConcreteRoboTwinRuntime",
    "EvoProxyStateAdapter",
    "FamilyRolloutRunner",
    "RoboTwinPins",
    "compute_divergence_curve",
    "compute_s1",
    "compute_s2",
    "compute_s3",
    "compute_s4",
    "compute_s5",
    "decide_stage_s",
    "evaluate_substrate",
    "family_collapse_metrics",
    "make_calibration_record",
    "matched_time_tau",
    "normalized_workspace_pose_rms",
    "select_calibration_setting",
    "select_published_tasks",
    "sha256_file",
    "verify_completion_bundle",
    "verify_completed_json",
    "verify_sha256sums",
    "write_completion",
    "write_sha256sums",
]
