"""Stage-S LIBERO substrate adapters and evidence-safe collection helpers.

This module deliberately contains no synthetic rollout path.  The B adapter
changes the simulator task (BDDL plus regenerated initial states), while the
C adapter only accepts complete, real pi05-LIBERO checkpoints.  The collection
helpers are adapter based so unit tests can use small fakes without importing
MuJoCo, JAX, or the PAI runtime.

The public functions are intentionally conservative:

* calibration returns and persists pooled counters only;
* a main-screen family is committed only after all data, genealogy, snapshot,
  metadata, and SHA files have been written and verified;
* restoring a Stage-R snapshot is checked by executing the same action twice
  and requiring an absolute next-state error of at most 1e-9.
"""

from __future__ import annotations

import copy
import hashlib
import importlib
import json
import math
import os
import pickle
import random
import re
import shutil
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Sequence

import numpy as np


STAGE_S_PROTOCOL_ID = "r142-stage-s-v1"
LIBERO_SUITE = "libero_10"
TASK_COUNT = 10
MAIN_INITIAL_STATE_COUNT = 16
MAIN_CANDIDATE_COUNT = 32
CALIBRATION_TASK_IDS = (0, 3, 6, 9)
CALIBRATION_INITIAL_STATES = tuple(range(8))
CALIBRATION_CANDIDATE_COUNT = 8
CALIBRATION_TARGET_SUCCESS = 0.45
MAIN_ACTION_HORIZON = 10
REPLAN_STEPS = 5
SNAPSHOT_REPLAY_TOLERANCE = 1e-9
FULL_PI05_LIBERO_TRAINING_STEPS = 30_000
UNDERTRAINED_CHECKPOINT_COUNT = 4

# C is a deliberately short, real pi05_libero training lineage.  These
# values are part of the frozen Stage-S substrate screen; callers cannot tune
# them through the launcher-contract helper.
C_TRAINING_SEED = 42
C_TRAINING_STEPS = 10_001
C_SAVE_INTERVAL = 1_000
C_RETAIN_STEPS = (1_000, 3_000, 6_000, 10_000)
C_FULL_REFERENCE_STEP = FULL_PI05_LIBERO_TRAINING_STEPS

# B initial states are regenerated by the real LIBERO/MuJoCo simulator after
# the duplicate is inserted.  The old .pruned_init tensor is only an audit
# input (for dimensionality/identity checks), never a generation input.
B_INIT_STATE_COUNT = 16
B_INIT_STATE_SEED_BASE = 142011

PAI_MAX_GPU = 8
PAI_MAX_CPU = 88
PAI_MAX_MEMORY_GIB = 1525
PAI_ROBOT_IDLE_RESOURCE_ALIAS = "idle-a800-robot-stage-s-graphics-8gpu"
PAI_ROBOT_IDLE_RESOURCE_ID = "quota1ssrabud0bh"
PAI_ROBOT_IDLE_QUOTA_NAME = "exp-robot"

# The four B settings are measured in the table's XY coordinate system.  They
# are frozen here rather than selected after observing any S2--S5 statistic.
# The minimum 0.06 m keeps a same-mesh duplicate from being intentionally
# interpenetrating at reset; all settings remain a local referential cue.
PROXIMITY_MAGNITUDES = (0.06, 0.08, 0.10, 0.12)


LIBERO_10_TASK_NAMES = (
    "LIVING_ROOM_SCENE2_put_both_the_alphabet_soup_and_the_tomato_sauce_in_the_basket",
    "LIVING_ROOM_SCENE2_put_both_the_cream_cheese_box_and_the_butter_in_the_basket",
    "KITCHEN_SCENE3_turn_on_the_stove_and_put_the_moka_pot_on_it",
    "KITCHEN_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet_and_close_it",
    "LIVING_ROOM_SCENE5_put_the_white_mug_on_the_left_plate_and_put_the_yellow_and_white_mug_on_the_right_plate",
    "STUDY_SCENE1_pick_up_the_book_and_place_it_in_the_back_compartment_of_the_caddy",
    "LIVING_ROOM_SCENE6_put_the_white_mug_on_the_plate_and_put_the_chocolate_pudding_to_the_right_of_the_plate",
    "LIVING_ROOM_SCENE1_put_both_the_alphabet_soup_and_the_cream_cheese_box_in_the_basket",
    "KITCHEN_SCENE8_put_both_moka_pots_on_the_stove",
    "KITCHEN_SCENE6_put_the_yellow_and_white_mug_in_the_microwave_and_close_it",
)


@dataclass(frozen=True)
class LiberoTaskSpec:
    """Frozen Stage-R task identity and the target used by B."""

    task_id: int
    name: str
    prompt: str
    target_object: str
    target_region: str


LIBERO_TASK_SPECS = (
    LiberoTaskSpec(0, LIBERO_10_TASK_NAMES[0], "put both the alphabet soup and the tomato sauce in the basket", "alphabet_soup_1", "alphabet_soup_init_region"),
    LiberoTaskSpec(1, LIBERO_10_TASK_NAMES[1], "put both the cream cheese box and the butter in the basket", "cream_cheese_1", "cream_cheese_init_region"),
    LiberoTaskSpec(2, LIBERO_10_TASK_NAMES[2], "turn on the stove and put the moka pot on it", "moka_pot_1", "moka_pot_init_region"),
    LiberoTaskSpec(3, LIBERO_10_TASK_NAMES[3], "put the black bowl in the bottom drawer of the cabinet and close it", "akita_black_bowl_1", "akita_black_bowl_init_region"),
    LiberoTaskSpec(4, LIBERO_10_TASK_NAMES[4], "put the white mug on the left plate and put the yellow and white mug on the right plate", "porcelain_mug_1", "porcelain_mug_init_region"),
    LiberoTaskSpec(5, LIBERO_10_TASK_NAMES[5], "pick up the book and place it in the back compartment of the caddy", "black_book_1", "black_book_init_region"),
    LiberoTaskSpec(6, LIBERO_10_TASK_NAMES[6], "put the white mug on the plate and put the chocolate pudding to the right of the plate", "porcelain_mug_1", "porcelain_mug_init_region"),
    LiberoTaskSpec(7, LIBERO_10_TASK_NAMES[7], "put both the alphabet soup and the cream cheese box in the basket", "alphabet_soup_1", "alphabet_soup_init_region"),
    LiberoTaskSpec(8, LIBERO_10_TASK_NAMES[8], "put both moka pots on the stove", "moka_pot_1", "moka_pot_right_init_region"),
    LiberoTaskSpec(9, LIBERO_10_TASK_NAMES[9], "put the yellow and white mug in the microwave and close it", "white_yellow_mug_1", "white_yellow_mug_init_region"),
)


class StageSError(RuntimeError):
    """Base class for fail-closed Stage-S errors."""


class VariantGenerationError(StageSError):
    pass


class MissingRegeneratedInitialStates(StageSError):
    pass


class CheckpointQualificationError(StageSError):
    pass


class SnapshotReplayError(StageSError):
    pass


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False)


def stable_seed(*parts: object, bytes_count: int = 8) -> int:
    payload = "|".join(str(part) for part in parts).encode("utf-8")
    return int.from_bytes(hashlib.sha256(payload).digest()[:bytes_count], "big", signed=False)


def _fsync_directory(path: Path) -> None:
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def atomic_bytes(path: str | Path, payload: bytes) -> None:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.tmp-{os.getpid()}")
    with temporary.open("wb") as handle:
        handle.write(payload)
        handle.flush()
        os.fsync(handle.fileno())
    temporary.replace(destination)
    _fsync_directory(destination.parent)


def atomic_json(path: str | Path, payload: Any) -> None:
    atomic_bytes(path, (json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False) + "\n").encode("utf-8"))


def atomic_text(path: str | Path, payload: str) -> None:
    atomic_bytes(path, payload.encode("utf-8"))


def atomic_npz(path: str | Path, payload: Mapping[str, np.ndarray]) -> None:
    import io

    buffer = io.BytesIO()
    np.savez_compressed(buffer, **payload)
    atomic_bytes(path, buffer.getvalue())


def _find_block(text: str, name: str) -> tuple[int, int]:
    """Find a balanced BDDL form whose first symbol is ``name``."""

    pattern = re.compile(rf"(?m)^[ \t]*\({re.escape(name)}(?=[\s)])")
    match = pattern.search(text)
    if match is None:
        raise VariantGenerationError(f"BDDL form {name!r} not found")
    start = match.start() + len(match.group(0)) - len(match.group(0).lstrip())
    depth = 0
    for index in range(start, len(text)):
        char = text[index]
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return start, index + 1
    raise VariantGenerationError(f"unterminated BDDL form {name!r}")


def _insert_before_form_close(text: str, block: tuple[int, int], line: str) -> str:
    start, end = block
    prefix = "" if text[: end - 1].endswith("\n") else "\n"
    return text[: end - 1] + prefix + line.rstrip("\n") + "\n" + text[end - 1 :]


def _object_type(objects_form: str, target_object: str) -> str:
    for line in objects_form.splitlines():
        if "-" not in line:
            continue
        lhs, rhs = line.split("-", 1)
        if target_object in lhs.split():
            values = rhs.strip().split()
            if values:
                return values[0]
    raise VariantGenerationError(f"target object {target_object!r} absent from (:objects)")


def _region_range(region_form: str) -> tuple[float, float, float, float]:
    ranges = re.search(
        r"\(:ranges\s*\(\s*\(\s*([^()]+?)\s*\)\s*\)",
        region_form,
        flags=re.DOTALL,
    )
    if ranges is None:
        raise VariantGenerationError("target region has no one-rectangle (:ranges) form")
    values = [float(value) for value in ranges.group(1).split()]
    if len(values) != 4 or not all(math.isfinite(value) for value in values):
        raise VariantGenerationError(f"invalid target region range: {values!r}")
    return tuple(values)  # type: ignore[return-value]


def _format_range(values: Sequence[float]) -> str:
    return " ".join(f"{float(value):.12g}" for value in values)


def _range_form(name: str, target: str, values: Sequence[float]) -> str:
    return (
        f"      ({name}\n"
        f"          (:target {target})\n"
        f"          (:ranges (\n"
        f"              ({_format_range(values)})\n"
        f"            )\n"
        f"          )\n"
        f"          (:yaw_rotation (\n"
        f"              (0.0 0.0)\n"
        f"            )\n"
        f"          )\n"
        f"      )"
    )


@dataclass(frozen=True)
class BVariant:
    """One deterministic BDDL variant for one task and magnitude."""

    task: LiberoTaskSpec
    magnitude: float
    source_bddl_path: str
    source_bddl_sha256: str
    bddl_text: str
    target_type: str
    distractor_object: str
    distractor_region: str
    target_center: tuple[float, float]
    distractor_center: tuple[float, float]
    offset_direction: tuple[float, float]
    prompt_unchanged: bool = True

    @property
    def setting_id(self) -> str:
        return f"proximity_{self.magnitude:.2f}m"

    def manifest(self) -> dict[str, Any]:
        return {
            "protocol_id": STAGE_S_PROTOCOL_ID,
            "substrate": "B",
            "suite": LIBERO_SUITE,
            "task_id": self.task.task_id,
            "task_name": self.task.name,
            "prompt": self.task.prompt,
            "prompt_unchanged": self.prompt_unchanged,
            "magnitude_m": self.magnitude,
            "target_object": self.task.target_object,
            "target_type": self.target_type,
            "distractor_object": self.distractor_object,
            "distractor_region": self.distractor_region,
            "target_center": list(self.target_center),
            "distractor_center": list(self.distractor_center),
            "offset_direction": list(self.offset_direction),
            "source_bddl_path": self.source_bddl_path,
            "source_bddl_sha256": self.source_bddl_sha256,
            "bddl_sha256": sha256_bytes(self.bddl_text.encode("utf-8")),
            "initial_states_contract": "regenerated_variant_qpos_required; original init qpos is incompatible",
        }


def task_spec(task_id: int) -> LiberoTaskSpec:
    value = int(task_id)
    if not 0 <= value < TASK_COUNT:
        raise ValueError(f"task_id must be in [0,{TASK_COUNT}), got {task_id!r}")
    return LIBERO_TASK_SPECS[value]


def generate_b_variant(
    source_bddl_path: str | Path,
    task_id: int,
    magnitude: float,
    *,
    offset_direction: tuple[float, float] | None = None,
) -> BVariant:
    """Generate an exact-one same-type duplicate without changing the goal.

    The insertion is purely textual and preserves the original ``(:language)``
    and ``(:goal)`` forms.  The duplicate is not put in ``obj_of_interest`` or
    ``goal``; it is therefore a visually identical referential distractor, not
    a second goal object.
    """

    magnitude = float(magnitude)
    if not any(math.isclose(magnitude, value, rel_tol=0.0, abs_tol=1e-12) for value in PROXIMITY_MAGNITUDES):
        raise VariantGenerationError(f"magnitude {magnitude!r} is not one of frozen settings {PROXIMITY_MAGNITUDES}")
    task = task_spec(task_id)
    path = Path(source_bddl_path)
    source = path.read_text(encoding="utf-8")
    source_sha = sha256_file(path)
    language = re.search(r"\(:language\s+([^\n)]+)\)", source)
    if language is None or language.group(1).strip() != task.prompt:
        raise VariantGenerationError(f"prompt mismatch in {path}: expected {task.prompt!r}")
    objects_start, objects_end = _find_block(source, ":objects")
    # _find_block expects a symbol that starts after '('; sections with a
    # colon use a direct fallback because BDDL names the form (:objects ...).
    objects_form = source[objects_start:objects_end]
    target_type = _object_type(objects_form, task.target_object)
    region_start, region_end = _find_block(source, task.target_region)
    target_range = _region_range(source[region_start:region_end])
    regions_start, regions_end = _find_block(source, ":regions")
    region_targets = re.findall(
        r"\(:target\s+([^\s)]+)\)", source[regions_start:regions_end]
    )
    table_target = next(
        (value for value in region_targets if value.endswith("_table")), None
    )
    if table_target is None:
        raise VariantGenerationError("could not identify the task table fixture in (:regions)")
    target_center = ((target_range[0] + target_range[2]) / 2.0, (target_range[1] + target_range[3]) / 2.0)
    direction = offset_direction or ((1.0, 0.0) if task_id % 2 == 0 else (0.0, 1.0))
    norm = math.hypot(*direction)
    if not math.isfinite(norm) or norm <= 0.0:
        raise VariantGenerationError("offset_direction must be finite and nonzero")
    direction = (float(direction[0] / norm), float(direction[1] / norm))
    distractor_center = (
        target_center[0] + magnitude * direction[0],
        target_center[1] + magnitude * direction[1],
    )
    width = target_range[2] - target_range[0]
    height = target_range[3] - target_range[1]
    duplicate_range = (
        distractor_center[0] - width / 2.0,
        distractor_center[1] - height / 2.0,
        distractor_center[0] + width / 2.0,
        distractor_center[1] + height / 2.0,
    )
    base_object = task.target_object.removesuffix("_1")
    distractor_object = f"{base_object}_distractor_1"
    distractor_region = f"{base_object}_distractor_init_region"
    if re.search(rf"\b{re.escape(distractor_object)}\b", source) or re.search(rf"\b{re.escape(distractor_region)}\b", source):
        raise VariantGenerationError("source already contains the reserved distractor names")
    # BDDL's parser groups object names by type and overwrites a type when it
    # appears in a second declaration.  Add the duplicate to the target's
    # existing type declaration instead of appending a second ``- type``
    # clause, otherwise the original target silently disappears at runtime.
    object_pattern = re.compile(
        rf"(?m)^(?P<line>[ \t][^()\n]*?\b{re.escape(task.target_object)}\b[^()\n]*-\s*{re.escape(target_type)}\s*)$"
    )
    object_match = object_pattern.search(source[objects_start:objects_end])
    if object_match is None:
        raise VariantGenerationError(
            f"could not find target declaration {task.target_object!r} - {target_type!r} in (:objects)"
        )
    object_form = object_match.group("line")
    object_form = re.sub(
        rf"\b{re.escape(task.target_object)}\b",
        f"{task.target_object} {distractor_object}",
        object_form,
        count=1,
    )
    object_start = objects_start + object_match.start("line")
    object_end = objects_start + object_match.end("line")
    source = source[:object_start] + object_form + source[object_end:]
    # Re-find blocks after the object insertion because offsets changed.
    source = _insert_before_form_close(
        source,
        _find_block(source, ":regions"),
        _range_form(distractor_region, table_target, duplicate_range),
    )
    source = _insert_before_form_close(
        source,
        _find_block(source, ":init"),
        f"    (On {distractor_object} {table_target}_{distractor_region})",
    )
    # Exact one duplicate: one declaration, one placement, zero goal mentions.
    if source.count(distractor_object) != 2 or distractor_object in source[source.find("(:goal") :]:
        raise VariantGenerationError("generated BDDL does not contain exactly one non-goal distractor")
    return BVariant(
        task=task,
        magnitude=magnitude,
        source_bddl_path=str(path),
        source_bddl_sha256=source_sha,
        bddl_text=source,
        target_type=target_type,
        distractor_object=distractor_object,
        distractor_region=distractor_region,
        target_center=target_center,
        distractor_center=distractor_center,
        offset_direction=direction,
    )


def _candidate_state_file(root: Path, task: LiberoTaskSpec) -> Path:
    return root / f"{task.name}.pruned_init"


def _existing_candidate_state_file(root: Path, task: LiberoTaskSpec) -> Path:
    """Resolve a generated state from either a staging root or B output root."""

    direct = _candidate_state_file(root, task)
    if direct.is_file():
        return direct
    nested = root / "init_states" / LIBERO_SUITE / direct.name
    if nested.is_file():
        return nested
    return direct


def validate_regenerated_initial_states(
    regenerated_root: str | Path,
    source_init_root: str | Path,
    tasks: Iterable[int] = range(TASK_COUNT),
    *,
    manifest_name: str = "REGENERATED_INIT_STATES.json",
) -> dict[str, Any]:
    """Require an explicit regenerated-qpos manifest before a B run.

    A BDDL edit changes MuJoCo's free-joint layout.  Copying the old tensor is
    invalid even if its first elements happen to load.  The manifest is an
    auditable hand-off from a real simulator regeneration job and must assert
    that old qpos was not reused.
    """

    regenerated = Path(regenerated_root)
    source = Path(source_init_root)
    marker = regenerated / manifest_name
    errors: list[str] = []
    if not marker.is_file():
        errors.append(f"missing {manifest_name}; old init qpos cannot be accepted")
        return {"valid": False, "errors": errors, "files": []}
    try:
        payload = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {"valid": False, "errors": [f"invalid regenerated-state manifest: {exc}"], "files": []}
    if payload.get("regenerated") is not True or payload.get("old_init_reused") is not False:
        errors.append("manifest must assert regenerated=true and old_init_reused=false")
    files: list[dict[str, Any]] = []
    for task_id in tasks:
        task = task_spec(task_id)
        path = _existing_candidate_state_file(regenerated, task)
        old = _candidate_state_file(source, task)
        if not path.is_file():
            errors.append(f"missing regenerated init file: {path}")
            continue
        new_sha = sha256_file(path)
        old_sha = sha256_file(old) if old.is_file() else None
        if old_sha is not None and new_sha == old_sha:
            errors.append(f"regenerated init file is byte-identical to old qpos: {path.name}")
        # When the generator persisted per-file hashes, compare the bytes we
        # are about to consume with both manifest forms.  The staging
        # manifest uses a task-row list while the copied B variant marker uses
        # a task-id keyed mapping; accepting either keeps the audit useful for
        # both hand-off points without silently trusting a stale file.
        expected_hashes: list[str] = []
        task_rows = payload.get("tasks")
        if isinstance(task_rows, list):
            for row in task_rows:
                if isinstance(row, Mapping) and int(row.get("task_id", -1)) == int(task_id):
                    value = row.get("sha256")
                    if value:
                        expected_hashes.append(str(value))
        file_hashes = payload.get("files")
        if isinstance(file_hashes, Mapping):
            for key in (str(task_id), task.name):
                value = file_hashes.get(key)
                if value:
                    expected_hashes.append(str(value))
        for expected_hash in sorted(set(expected_hashes)):
            if new_sha != expected_hash:
                errors.append(
                    f"regenerated init hash mismatch for {path.name}: observed {new_sha}, expected {expected_hash}"
                )
        record = {"task_id": int(task_id), "path": str(path), "sha256": new_sha, "old_sha256": old_sha}
        # A simulator-generated manifest may opt into the stronger tensor
        # checks below.  Legacy unit fixtures intentionally use opaque bytes;
        # they remain accepted only when the manifest does not claim a qpos
        # serialization format.
        if payload.get("qpos_format"):
            try:
                array = _load_qpos_array(path)
            except Exception as exc:  # noqa: BLE001 - fail closed in result
                errors.append(f"cannot load regenerated qpos {path.name}: {exc}")
            else:
                minimum = int(payload.get("init_state_count", B_INIT_STATE_COUNT))
                if array.ndim != 2 or array.shape[0] < minimum:
                    errors.append(f"regenerated qpos {path.name} has shape {array.shape}, expected >=({minimum}, dim)")
                record["qpos_shape"] = list(array.shape)
        files.append(record)
    return {"valid": not errors, "errors": errors, "files": files, "manifest": payload}


def write_b_variant(
    variant: BVariant,
    output_root: str | Path,
    *,
    regenerated_initial_states_root: str | Path | None,
    source_init_root: str | Path,
    write_config: bool = True,
    assets_root: str | Path | None = None,
) -> dict[str, Any]:
    """Write one B variant and its *separately regenerated* init states."""

    if regenerated_initial_states_root is None:
        raise MissingRegeneratedInitialStates("B requires regenerated initial qpos; no source-only fallback is permitted")
    audit = validate_regenerated_initial_states(
        regenerated_initial_states_root,
        source_init_root,
        tasks=(variant.task.task_id,),
    )
    if not audit["valid"]:
        raise MissingRegeneratedInitialStates("; ".join(audit["errors"]))
    root = Path(output_root)
    bddl_dir = root / "bddl_files" / LIBERO_SUITE
    init_dir = root / "init_states" / LIBERO_SUITE
    bddl_dir.mkdir(parents=True, exist_ok=True)
    init_dir.mkdir(parents=True, exist_ok=True)
    bddl_path = bddl_dir / f"{variant.task.name}.bddl"
    init_source = _candidate_state_file(Path(regenerated_initial_states_root), variant.task)
    init_path = init_dir / init_source.name
    atomic_text(bddl_path, variant.bddl_text)
    atomic_bytes(init_path, init_source.read_bytes())
    if write_config:
        config = {
            "benchmark_root": str(root.resolve()),
            "bddl_files": str((root / "bddl_files").resolve()),
            "init_states": str((root / "init_states").resolve()),
            "datasets": str((root / "datasets").resolve()),
            "assets": str(Path(assets_root).resolve()) if assets_root else "",
        }
        atomic_text(root / "config.yaml", "\n".join(f"{key}: {value}" for key, value in config.items()) + "\n")
    result = variant.manifest()
    result.update({"bddl_path": str(bddl_path), "init_states_path": str(init_path), "init_states_sha256": sha256_file(init_path)})
    atomic_json(root / f"{variant.task.name}.{variant.setting_id}.json", result)
    return result


def build_b_variant_suite(
    source_bddl_root: str | Path,
    output_root: str | Path,
    magnitude: float,
    *,
    regenerated_initial_states_root: str | Path | None,
    source_init_root: str | Path,
    assets_root: str | Path | None = None,
) -> list[dict[str, Any]]:
    """Build all ten task files, failing before writes if qpos is absent."""

    if regenerated_initial_states_root is None:
        raise MissingRegeneratedInitialStates("B suite build requires regenerated init states for every task")
    audit = validate_regenerated_initial_states(regenerated_initial_states_root, source_init_root)
    if not audit["valid"]:
        raise MissingRegeneratedInitialStates("; ".join(audit["errors"]))
    source_root = Path(source_bddl_root)
    results = []
    for task_id in range(TASK_COUNT):
        task = task_spec(task_id)
        source_path = source_root / f"{task.name}.bddl"
        variant = generate_b_variant(source_path, task_id, magnitude)
        results.append(
            write_b_variant(
                variant,
                output_root,
                regenerated_initial_states_root=regenerated_initial_states_root,
                source_init_root=source_init_root,
                assets_root=assets_root,
                write_config=task_id == 0,
            )
        )
    return results


def _load_qpos_array(path: str | Path) -> np.ndarray:
    """Load a LIBERO ``.pruned_init`` tensor without changing its contents."""

    target = Path(path)
    errors: list[str] = []
    try:
        import torch

        try:
            value = torch.load(target, map_location="cpu", weights_only=False)
        except TypeError:  # torch versions before the weights_only argument
            value = torch.load(target, map_location="cpu")
        if hasattr(value, "detach"):
            value = value.detach().cpu().numpy()
        array = np.asarray(value, dtype=np.float64)
    except Exception as exc:  # noqa: BLE001 - try the NumPy fallback below
        errors.append(f"torch.load: {exc}")
        try:
            value = np.load(target, allow_pickle=False)
            if isinstance(value, np.lib.npyio.NpzFile):
                keys = list(value.files)
                if len(keys) != 1:
                    raise ValueError(f"expected one array in npz, got {keys}")
                value = value[keys[0]]
            array = np.asarray(value, dtype=np.float64)
        except Exception as fallback_exc:  # noqa: BLE001 - report both causes
            errors.append(f"numpy.load: {fallback_exc}")
            raise VariantGenerationError(f"cannot load qpos tensor {target}: {'; '.join(errors)}") from fallback_exc
    if array.ndim == 1:
        array = array[None, :]
    if array.ndim != 2 or not np.all(np.isfinite(array)):
        raise VariantGenerationError(f"qpos tensor {target} must be finite rank-2, got {array.shape}")
    return array


def _write_torch_qpos(path: str | Path, array: np.ndarray) -> None:
    """Atomically write a simulator-generated tensor in LIBERO's format."""

    try:
        import torch
    except Exception as exc:  # noqa: BLE001 - this is an external runtime gate
        raise VariantGenerationError("real B qpos generation requires torch.save") from exc
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.tmp-{os.getpid()}")
    torch.save(torch.as_tensor(np.asarray(array, dtype=np.float64)), temporary)
    with temporary.open("rb") as handle:
        os.fsync(handle.fileno())
    temporary.replace(destination)
    _fsync_directory(destination.parent)


def _qpos_from_simulator(environment: Any) -> np.ndarray:
    """Read qpos from an OffScreenRenderEnv or a Task64Environment wrapper."""

    pending = [environment]
    seen: set[int] = set()
    while pending:
        owner = pending.pop(0)
        if owner is None or id(owner) in seen:
            continue
        seen.add(id(owner))
        sim = getattr(owner, "sim", None)
        data = getattr(sim, "data", None)
        qpos = getattr(data, "qpos", None)
        if qpos is not None:
            array = np.asarray(qpos, dtype=np.float64).reshape(-1)
            if array.size and np.all(np.isfinite(array)):
                return array.copy()
        for name in ("environment", "env", "unwrapped", "base"):
            child = getattr(owner, name, None)
            if child is not None:
                pending.append(child)
    raise VariantGenerationError("simulator does not expose finite sim.data.qpos")


def _seed_simulator(environment: Any, seed: int) -> None:
    # LIBERO's BDDL environment delegates to ``numpy.random.seed``, whose
    # legacy API accepts only uint32 seeds.  Keep the manifest's deterministic
    # seed identity while passing the portable uint32 value to real wrappers.
    simulator_seed = int(seed) & 0xFFFFFFFF
    for owner in (environment, getattr(environment, "environment", None)):
        setter = getattr(owner, "seed", None)
        if callable(setter):
            setter(simulator_seed)


def _call_qpos_simulator_factory(
    simulator_factory: Callable[..., Any],
    task_id: int,
    bddl_path: Path,
    seed: int,
) -> Any:
    try:
        return simulator_factory(task_id=int(task_id), bddl_path=str(bddl_path), seed=int(seed))
    except TypeError as keyword_error:
        try:
            return simulator_factory(int(task_id), str(bddl_path), int(seed))
        except TypeError:
            raise keyword_error


def b_init_state_seed(task_id: int, setting_index: int, state_index: int, *, seed_base: int = B_INIT_STATE_SEED_BASE) -> int:
    """Return the frozen deterministic seed for one new B init state."""

    return stable_seed(
        "stage-s", "B", "qpos", int(seed_base), int(setting_index), int(task_id), int(state_index), bytes_count=4
    )


def generate_variant_initial_qpos(
    simulator_factory: Callable[..., Any],
    output_path: str | Path,
    *,
    task_id: int,
    bddl_path: str | Path,
    source_init_path: str | Path,
    count: int = B_INIT_STATE_COUNT,
    seeds: Sequence[int] | None = None,
    qpos_writer: Callable[[str | Path, np.ndarray], None] | None = None,
    require_unique: bool = True,
) -> dict[str, Any]:
    """Generate new qpos rows by resetting the real simulator with fixed seeds.

    The simulator is reset from the generated BDDL itself; no old init state is
    passed to it.  The source tensor is loaded only to prove that the free-joint
    layout grew and that no generated row is an exact old row.
    """

    if int(count) < B_INIT_STATE_COUNT:
        raise VariantGenerationError(f"B requires at least {B_INIT_STATE_COUNT} generated init states, got {count}")
    source_path = Path(source_init_path)
    if not source_path.is_file():
        raise VariantGenerationError(f"missing source init tensor for audit: {source_path}")
    old_array = _load_qpos_array(source_path)
    selected_seeds = tuple(int(value) for value in (seeds if seeds is not None else range(int(count))))
    if len(selected_seeds) != int(count):
        raise VariantGenerationError(f"expected {count} fixed seeds, got {len(selected_seeds)}")
    rows: list[np.ndarray] = []
    for seed in selected_seeds:
        python_state = random.getstate()
        numpy_state = np.random.get_state()
        environment = None
        try:
            random.seed(int(seed))
            np.random.seed(int(seed) & 0xFFFFFFFF)
            environment = _call_qpos_simulator_factory(simulator_factory, int(task_id), Path(bddl_path), int(seed))
            _seed_simulator(environment, int(seed))
            reset = getattr(environment, "reset", None)
            if not callable(reset):
                raise VariantGenerationError("qpos simulator has no reset()")
            try:
                reset()
            except TypeError:
                reset(seed=int(seed))
            rows.append(_qpos_from_simulator(environment))
        finally:
            if environment is not None and hasattr(environment, "close"):
                environment.close()
            random.setstate(python_state)
            np.random.set_state(numpy_state)
    try:
        generated = np.stack(rows, axis=0).astype(np.float64, copy=False)
    except ValueError as exc:
        raise VariantGenerationError(f"generated qpos rows have inconsistent dimensions: {[row.shape for row in rows]}") from exc
    if generated.shape[0] < B_INIT_STATE_COUNT or generated.shape[0] != int(count):
        raise VariantGenerationError(f"generated qpos has invalid row count {generated.shape[0]}")
    if generated.shape[1] <= old_array.shape[1]:
        raise VariantGenerationError(
            f"B qpos dimension did not grow after duplicate insertion: old={old_array.shape[1]}, new={generated.shape[1]}"
        )
    if require_unique and len({sha256_bytes(row.tobytes()) for row in generated}) != generated.shape[0]:
        raise VariantGenerationError("simulator produced duplicate qpos rows; refusing to call them new init states")
    for row in generated:
        if old_array.shape[1] == generated.shape[1] and any(np.array_equal(row, old) for old in old_array):
            raise VariantGenerationError("simulator-generated qpos contains an exact old init row")
    writer = qpos_writer or _write_torch_qpos
    writer(output_path, generated)
    destination = Path(output_path)
    if not destination.is_file():
        raise VariantGenerationError(f"qpos writer did not create {destination}")
    return {
        "task_id": int(task_id),
        "path": str(destination),
        "sha256": sha256_file(destination),
        "count": int(generated.shape[0]),
        "qpos_dim": int(generated.shape[1]),
        "source_qpos_dim": int(old_array.shape[1]),
        "seeds": [int(value) for value in selected_seeds],
        "generated_by": "real_libero_offscreen_render_env_reset",
        "old_init_reused": False,
    }


def _resolve_libero_site(libero_root: str | Path) -> Path:
    root = Path(libero_root).resolve()
    # The pinned OpenPI LIBERO fork has a namespace-level ``libero`` folder
    # containing the import package ``libero.libero``.  Accept its project
    # root, namespace root, or inner package path and always return the path
    # that makes ``import libero.libero`` resolve to that fork.  Also support
    # the flatter upstream ``import libero`` layout for a qpos-only smoke.
    if (root / "libero" / "libero" / "envs" / "__init__.py").is_file():
        return root
    if (
        ((root / "setup.py").is_file() or (root.parent / "setup.py").is_file())
        and (root / "libero" / "__init__.py").is_file()
        and (root / "libero" / "envs" / "__init__.py").is_file()
    ):
        return root if (root / "setup.py").is_file() else root.parent
    if (root / "envs" / "__init__.py").is_file() and (root / "__init__.py").is_file():
        return root.parent.parent
    if (root / "libero" / "__init__.py").is_file() and (root / "libero" / "bddl_files").is_dir():
        return root
    if (root / "envs" / "__init__.py").is_file():
        return root.parent
    return root


def make_libero_qpos_simulator_factory(
    libero_root: str | Path,
    *,
    render_gpu_device_id: int = 0,
    camera_height: int = 256,
    camera_width: int = 256,
) -> Callable[..., Any]:
    """Build a factory around the pinned LIBERO OffScreenRenderEnv.

    Imports are intentionally deferred until the first real generation call,
    so CPU-only unit tests never require MuJoCo or the external site package.
    """

    site = _resolve_libero_site(libero_root)

    def factory(*, task_id: int, bddl_path: str, seed: int) -> Any:
        del task_id
        os.environ["QPILOTS_LIBERO_SITE"] = str(site)
        if str(site) not in sys.path:
            sys.path.append(str(site))
        try:
            from libero.libero.envs import OffScreenRenderEnv
        except ModuleNotFoundError as nested_error:
            # A flat LIBERO installation is accepted only for the isolated
            # qpos smoke; Stage-R's maintained wrapper still requires the
            # nested OpenPI fork and will fail closed if it is absent.
            try:
                from libero.envs import OffScreenRenderEnv
            except Exception as flat_error:  # noqa: BLE001 - preserve both import causes
                raise VariantGenerationError(
                    f"cannot import pinned LIBERO OffScreenRenderEnv from {site}: {nested_error}; {flat_error}"
                ) from flat_error
        except Exception as exc:  # noqa: BLE001 - retain the external-runtime cause
            raise VariantGenerationError(f"cannot import pinned LIBERO OffScreenRenderEnv from {site}: {exc}") from exc
        environment = OffScreenRenderEnv(
            bddl_file_name=str(Path(bddl_path).resolve()),
            camera_heights=int(camera_height),
            camera_widths=int(camera_width),
            camera_names=("agentview", "robot0_eye_in_hand"),
            render_gpu_device_id=int(render_gpu_device_id),
        )
        _seed_simulator(environment, int(seed))
        return environment

    return factory


def build_b_variant_matrix(
    source_bddl_root: str | Path,
    source_init_root: str | Path,
    output_root: str | Path,
    *,
    simulator_factory: Callable[..., Any],
    settings: Sequence[float] = PROXIMITY_MAGNITUDES,
    count: int = B_INIT_STATE_COUNT,
    seed_base: int = B_INIT_STATE_SEED_BASE,
    assets_root: str | Path | None = None,
) -> list[dict[str, Any]]:
    """Create all ten BDDL tasks at all four offsets and fresh simulator qpos."""

    frozen_settings = tuple(float(value) for value in settings)
    if frozen_settings != tuple(PROXIMITY_MAGNITUDES):
        raise VariantGenerationError(f"B settings are frozen to {PROXIMITY_MAGNITUDES}, got {frozen_settings}")
    source_bddl = Path(source_bddl_root)
    source_init = Path(source_init_root)
    destination = Path(output_root)
    # Validate the complete source set before creating any variant, so a
    # missing task cannot leave a misleading partially executable matrix.
    source_paths: dict[int, Path] = {}
    for task_id in range(TASK_COUNT):
        task = task_spec(task_id)
        bddl_path = source_bddl / f"{task.name}.bddl"
        init_path = source_init / f"{task.name}.pruned_init"
        if not bddl_path.is_file() or not init_path.is_file():
            raise MissingRegeneratedInitialStates(f"missing frozen LIBERO source task {task_id}: {bddl_path} / {init_path}")
        source_paths[task_id] = bddl_path
    manifests: list[dict[str, Any]] = []
    for setting_index, magnitude in enumerate(frozen_settings):
        setting_id = f"proximity_{magnitude:.2f}m"
        setting_root = destination / setting_id
        generated_root = setting_root / "generated_init_states"
        bddl_dir = setting_root / "bddl_files" / LIBERO_SUITE
        generated_root.mkdir(parents=True, exist_ok=True)
        bddl_dir.mkdir(parents=True, exist_ok=True)
        variants: list[BVariant] = []
        generations: list[dict[str, Any]] = []
        for task_id in range(TASK_COUNT):
            task = task_spec(task_id)
            variant = generate_b_variant(source_paths[task_id], task_id, magnitude)
            variant_bddl = bddl_dir / f"{task.name}.bddl"
            atomic_text(variant_bddl, variant.bddl_text)
            variants.append(variant)
            generations.append(
                generate_variant_initial_qpos(
                    simulator_factory,
                    generated_root / f"{task.name}.pruned_init",
                    task_id=task_id,
                    bddl_path=variant_bddl,
                    source_init_path=source_init / f"{task.name}.pruned_init",
                    count=int(count),
                    seeds=tuple(b_init_state_seed(task_id, setting_index, index, seed_base=int(seed_base)) for index in range(int(count))),
                )
            )
        generated_manifest = {
            "protocol_id": STAGE_S_PROTOCOL_ID,
            "substrate": "B",
            "suite": LIBERO_SUITE,
            "setting_id": setting_id,
            "magnitude_m": float(magnitude),
            "regenerated": True,
            "old_init_reused": False,
            "qpos_format": "torch.save",
            "init_state_count": int(count),
            "seed_base": int(seed_base),
            "generated_by": "real_libero_offscreen_render_env_reset",
            "tasks": generations,
        }
        atomic_json(generated_root / "REGENERATED_INIT_STATES.json", generated_manifest)
        task_results: list[dict[str, Any]] = []
        for task_id, variant in enumerate(variants):
            task_results.append(
                write_b_variant(
                    variant,
                    setting_root,
                    regenerated_initial_states_root=generated_root,
                    source_init_root=source_init,
                    assets_root=assets_root,
                    write_config=task_id == 0,
                )
            )
        generated_manifest["files"] = {
            str(task_result["task_id"]): task_result["init_states_sha256"] for task_result in task_results
        }
        atomic_json(setting_root / "REGENERATED_INIT_STATES.json", generated_manifest)
        manifests.append(
            {
                "protocol_id": STAGE_S_PROTOCOL_ID,
                "substrate": "B",
                "setting_id": setting_id,
                "magnitude_m": float(magnitude),
                "root": str(setting_root),
                "tasks": task_results,
                "regenerated_init_states": str(setting_root / "REGENERATED_INIT_STATES.json"),
            }
        )
    atomic_json(destination / "B_VARIANT_MATRIX.json", {"protocol_id": STAGE_S_PROTOCOL_ID, "substrate": "B", "settings": manifests})
    return manifests


def _configure_stage_r_sources(qpilots_root: str | Path, libero_root: str | Path) -> tuple[Path, Path]:
    """Apply the pinned Stage-R import roots without importing heavy runtimes."""

    qpilots = Path(qpilots_root).resolve()
    libero_site = _resolve_libero_site(libero_root)
    for value in (qpilots, libero_site):
        if str(value) not in sys.path:
            sys.path.insert(0, str(value))
    os.environ["QPILOTS_LIBERO_SITE"] = str(libero_site)
    return qpilots, libero_site


class StageRPolicyAdapter:
    """Adapter from the maintained Stage-R pi05 policy to Stage-S callbacks."""

    def __init__(
        self,
        checkpoint: str | Path,
        *,
        qpilots_root: str | Path,
        default_prompt: str,
        config_name: str = "pi05_libero",
    ) -> None:
        qpilots, _ = _configure_stage_r_sources(qpilots_root, Path(qpilots_root) / "third_party" / "openpi" / "third_party" / "libero" / "libero")
        try:
            module = importlib.import_module("qpilots_libero.policy")
            policy_class = getattr(module, "CleanPi05LiberoPolicy")
        except Exception as exc:  # noqa: BLE001 - preserve the real dependency error
            raise StageSError(f"cannot import pinned Stage-R CleanPi05LiberoPolicy from {qpilots}: {exc}") from exc
        target = Path(checkpoint).expanduser()
        if not target.exists() and not str(checkpoint).startswith(("gs://", "s3://")):
            raise StageSError(f"Stage-R policy checkpoint is missing: {target}")
        self.checkpoint = str(checkpoint)
        self.default_prompt = str(default_prompt)
        self.config_name = str(config_name)
        self.policy = policy_class(self.checkpoint, default_prompt=self.default_prompt, config_name=self.config_name)

    def sample_action_chunk(self, observation: Mapping[str, Any], *, seed: int, counter: int) -> np.ndarray:
        """Return the exact official 10x7 action chunk for one observation."""

        try:
            runtime = importlib.import_module("r142_stage_r.runtime")
            noise = runtime.policy_noise(self.policy, int(seed), int(counter))
            output = runtime.infer_physical_many(self.policy, [dict(observation)], np.asarray(noise)[None, ...])
        except Exception as exc:  # noqa: BLE001 - a real runtime failure is fatal
            raise StageSError(f"Stage-R policy inference failed; no synthetic fallback is allowed: {exc}") from exc
        actions = np.asarray(output, dtype=np.float32)
        if actions.shape != (1, MAIN_ACTION_HORIZON, 7) or not np.all(np.isfinite(actions)):
            raise StageSError(f"Stage-R policy returned {actions.shape}; expected (1,{MAIN_ACTION_HORIZON},7)")
        return actions[0]

    def checkpoint_identity(self) -> Mapping[str, Any]:
        identity = getattr(self.policy, "checkpoint_identity", None)
        if not callable(identity):
            raise StageSError("pinned Stage-R policy does not expose checkpoint_identity")
        value = identity()
        if not isinstance(value, Mapping):
            raise StageSError("checkpoint_identity must return a mapping")
        return dict(value)


def make_stage_r_policy_factory(
    qpilots_root: str | Path,
    checkpoint: str | Path,
    *,
    default_prompt: str | None = None,
    config_name: str = "pi05_libero",
) -> Callable[..., StageRPolicyAdapter]:
    """Return a factory for the existing Stage-R policy wrapper."""

    prompt = str(default_prompt or task_spec(0).prompt)

    def factory(*, prompt_override: str | None = None, **_: Any) -> StageRPolicyAdapter:
        return StageRPolicyAdapter(
            checkpoint,
            qpilots_root=qpilots_root,
            default_prompt=str(prompt_override or prompt),
            config_name=config_name,
        )

    return factory


def make_stage_r_task64_factory(
    qpilots_root: str | Path,
    libero_root: str | Path,
    *,
    checkpoint: str | Path | None = None,
    variant_root: str | Path | None = None,
    max_steps: int = 520,
    init_state_count: int | None = None,
    num_steps_wait: int = 10,
) -> Callable[..., Any]:
    """Return an environment factory backed by Stage-R's Task64Environment.

    The B variant root is installed before ``libero`` is first imported.  A
    variant with 16 generated states therefore uses ``init_state_count=16``;
    the unmodified A/C substrate keeps the pinned 50-state suite and selects
    the frozen first 16 indices at the Stage-S runner level.
    """

    qpilots, libero_site = _configure_stage_r_sources(qpilots_root, libero_root)
    variant = Path(variant_root).resolve() if variant_root is not None else None
    if variant is not None:
        marker = variant / "REGENERATED_INIT_STATES.json"
        if not marker.is_file():
            raise MissingRegeneratedInitialStates(f"B variant root has no regenerated-state marker: {marker}")
        os.environ["LIBERO_CONFIG_PATH"] = str(variant)
    state_count = int(init_state_count if init_state_count is not None else (B_INIT_STATE_COUNT if variant is not None else 50))
    if state_count <= 0:
        raise ValueError("init_state_count must be positive")
    if checkpoint is not None:
        checkpoint_path = Path(checkpoint).expanduser()
        if not checkpoint_path.exists() and not str(checkpoint).startswith(("gs://", "s3://")):
            raise StageSError(f"Stage-R environment checkpoint is missing: {checkpoint_path}")

    def factory(*, task_id: int, init_state: int, candidate_id: int, seed: int, variant: Any = None) -> Any:
        del candidate_id, variant
        if variant_root is not None:
            os.environ["LIBERO_CONFIG_PATH"] = str(Path(variant_root).resolve())
        try:
            environment_module = importlib.import_module("qpilots_libero.environment")
            environment_class = getattr(environment_module, "Task64Environment")
            config = {
                "task": {
                    "suite": LIBERO_SUITE,
                    "task_id": int(task_id),
                    "prompt": task_spec(int(task_id)).prompt,
                    "init_state_count": state_count,
                    "num_steps_wait": int(num_steps_wait),
                    "replan_steps": REPLAN_STEPS,
                    "max_steps": int(max_steps),
                }
            }
            return environment_class(config, seed=int(seed))
        except Exception as exc:  # noqa: BLE001 - preserve the real adapter error
            raise StageSError(
                f"cannot construct pinned Stage-R Task64Environment for task={task_id} from {qpilots} / {libero_site}: {exc}"
            ) from exc

    return factory


def seeded_reset(environment: Any, init_state: int, seed: int) -> Any:
    """Set every exposed environment seed before a deterministic reset."""

    target = getattr(environment, "environment", None)
    seed_owner = target if target is not None and hasattr(target, "seed") else environment
    # The maintained Task64 wrapper delegates to LIBERO's ``np.random.seed``;
    # use its uint32-compatible value while retaining the full seed in the
    # wrapper metadata/genealogy for auditability.
    environment_seed = int(seed) & 0xFFFFFFFF
    if hasattr(seed_owner, "seed"):
        seed_owner.seed(environment_seed)
    if hasattr(environment, "evaluation_seed"):
        environment.evaluation_seed = int(seed)
    reset = getattr(environment, "reset", None)
    if reset is None:
        raise StageSError("environment has no reset method")
    try:
        return reset(int(init_state))
    except TypeError:
        return reset(seed=int(seed))


def _observation(environment: Any) -> Any:
    if hasattr(environment, "raw_observation"):
        return environment.raw_observation()
    value = getattr(environment, "observation", None)
    return value() if callable(value) else value


def _state_vector(environment: Any, observation: Any = None) -> np.ndarray:
    for name in ("state_vector", "get_state_vector", "current_state_vector"):
        if hasattr(environment, name):
            value = getattr(environment, name)
            return np.asarray(value() if callable(value) else value, dtype=np.float64).reshape(-1)
    if isinstance(observation, Mapping):
        pieces = []
        for key in sorted(observation):
            if "image" in key.lower() or key == "prompt":
                continue
            value = np.asarray(observation[key])
            if np.issubdtype(value.dtype, np.number):
                pieces.append(value.astype(np.float64).reshape(-1))
        if pieces:
            return np.concatenate(pieces)
    if observation is not None:
        value = np.asarray(observation)
        if np.issubdtype(value.dtype, np.number):
            return value.astype(np.float64).reshape(-1)
    return np.zeros(1, dtype=np.float64)


def _pose_vector(environment: Any, observation: Any = None) -> np.ndarray:
    for name in ("pose_vector", "get_pose_vector", "current_pose_vector"):
        if hasattr(environment, name):
            value = getattr(environment, name)
            return np.asarray(value() if callable(value) else value, dtype=np.float64).reshape(-1)
    return _state_vector(environment, observation)


def _execute_one(environment: Any, action: np.ndarray) -> dict[str, Any]:
    action = np.asarray(action, dtype=np.float32)
    if hasattr(environment, "execute_actions"):
        try:
            result = environment.execute_actions(action[None, ...])
        except (TypeError, ValueError, IndexError):
            result = environment.execute_actions(action)
    elif hasattr(environment, "step"):
        result = environment.step(action)
    else:
        raise StageSError("environment has neither execute_actions nor step")
    if isinstance(result, tuple):
        # gym-style (obs, reward, terminated, truncated, info)
        if len(result) >= 5:
            result = {"done": bool(result[2] or result[3]), "success": bool(result[4].get("success", False)) if isinstance(result[4], Mapping) else False, "info": result[4]}
        elif len(result) >= 4:
            result = {"done": bool(result[2]), "success": False, "info": result[3]}
        else:
            result = {}
    if result is None:
        result = {}
    if not isinstance(result, Mapping):
        result = {"done": bool(getattr(result, "done", False))}
    output = dict(result)
    output.setdefault("success", bool(output.get("is_success", False)))
    output.setdefault("done", bool(output["success"]))
    return output


def _sample_chunk(policy: Any, observation: Any, seed: int, counter: int, action_count: int = REPLAN_STEPS) -> np.ndarray:
    if hasattr(policy, "sample_action_chunk"):
        actions = policy.sample_action_chunk(observation, seed=int(seed), counter=int(counter))
    elif hasattr(policy, "sample_action"):
        actions = [policy.sample_action(observation, seed=int(seed), counter=int(counter)) for _ in range(action_count)]
    else:
        raise StageSError("policy adapter must expose sample_action_chunk or sample_action")
    array = np.asarray(actions, dtype=np.float32)
    if array.ndim == 3 and array.shape[0] == 1:
        array = array[0]
    if array.ndim != 2 or array.shape[0] < action_count:
        raise StageSError(f"policy returned invalid action chunk shape {array.shape}")
    return array[:action_count].copy()


@dataclass
class StageRSnapshot:
    """Stage-R-compatible snapshot, with policy RNG state when exposed."""

    environment: Any
    observation_history: Any
    action_queue: list[np.ndarray]
    python_rng_state: object
    numpy_rng_state: object
    baseline_noise_seed: int
    baseline_noise_counter: int
    step: int
    policy_rng_state: Any = None


def _policy_rng_state(policy: Any) -> Any:
    for name in ("get_rng_state", "rng_state"):
        if hasattr(policy, name):
            value = getattr(policy, name)
            return copy.deepcopy(value() if callable(value) else value)
    return None


def _restore_policy_rng(policy: Any, state: Any) -> None:
    if state is None or policy is None:
        return
    setter = getattr(policy, "set_rng_state", None)
    if setter is not None:
        setter(copy.deepcopy(state))


def capture_stage_r_snapshot(environment: Any, action_queue: Sequence[np.ndarray], seed: int, counter: int, step: int, *, policy: Any = None) -> StageRSnapshot:
    if not hasattr(environment, "capture_snapshot"):
        raise SnapshotReplayError("Stage-R snapshot requires environment.capture_snapshot")
    history = getattr(environment, "_observation", None)
    if history is None:
        history = getattr(environment, "observation_history", None)
    return StageRSnapshot(
        environment=copy.deepcopy(environment.capture_snapshot()),
        observation_history=copy.deepcopy(history),
        action_queue=[np.asarray(value, dtype=np.float32).copy() for value in action_queue],
        python_rng_state=copy.deepcopy(random.getstate()),
        numpy_rng_state=copy.deepcopy(np.random.get_state()),
        baseline_noise_seed=int(seed),
        baseline_noise_counter=int(counter),
        step=int(step),
        policy_rng_state=_policy_rng_state(policy),
    )


def restore_stage_r_snapshot(environment: Any, snapshot: StageRSnapshot, *, policy: Any = None) -> list[np.ndarray]:
    if not hasattr(environment, "restore_snapshot"):
        raise SnapshotReplayError("Stage-R snapshot requires environment.restore_snapshot")
    if hasattr(environment, "evaluation_seed") and hasattr(snapshot.environment, "evaluation_seed"):
        environment.evaluation_seed = int(snapshot.environment.evaluation_seed)
    environment.restore_snapshot(copy.deepcopy(snapshot.environment))
    if snapshot.observation_history is not None:
        if hasattr(environment, "_observation"):
            environment._observation = copy.deepcopy(snapshot.observation_history)
        elif hasattr(environment, "observation_history"):
            environment.observation_history = copy.deepcopy(snapshot.observation_history)
    random.setstate(copy.deepcopy(snapshot.python_rng_state))
    np.random.set_state(copy.deepcopy(snapshot.numpy_rng_state))
    _restore_policy_rng(policy, snapshot.policy_rng_state)
    return [np.asarray(value, dtype=np.float32).copy() for value in snapshot.action_queue]


def _numeric_leaves(value: Any) -> list[np.ndarray]:
    if isinstance(value, np.ndarray):
        if np.issubdtype(value.dtype, np.number):
            return [value.astype(np.float64).reshape(-1)]
        return []
    if isinstance(value, Mapping):
        result: list[np.ndarray] = []
        for key in sorted(value, key=str):
            result.extend(_numeric_leaves(value[key]))
        return result
    if isinstance(value, (list, tuple)):
        result = []
        for item in value:
            result.extend(_numeric_leaves(item))
        return result
    if isinstance(value, (bool, int, float, np.number)):
        return [np.asarray([value], dtype=np.float64)]
    return []


def validate_restore_same_action(
    environment: Any,
    snapshot: StageRSnapshot,
    action: Iterable[float],
    *,
    second_environment: Any | None = None,
    policy: Any = None,
    tolerance: float = SNAPSHOT_REPLAY_TOLERANCE,
) -> dict[str, Any]:
    """Verify restore -> same action -> identical next state <= 1e-9."""

    action_array = np.asarray(action, dtype=np.float32)
    restore_stage_r_snapshot(environment, snapshot, policy=policy)
    _execute_one(environment, action_array)
    first = _state_vector(environment, _observation(environment))
    if second_environment is None:
        restore_stage_r_snapshot(environment, snapshot, policy=policy)
        _execute_one(environment, action_array)
        second = _state_vector(environment, _observation(environment))
    else:
        restore_stage_r_snapshot(second_environment, snapshot, policy=policy)
        _execute_one(second_environment, action_array)
        second = _state_vector(second_environment, _observation(second_environment))
    if first.shape != second.shape:
        error = float("inf")
    else:
        error = float(np.max(np.abs(first - second))) if first.size else 0.0
    result = {"passed": bool(error <= float(tolerance)), "max_abs_error": error, "tolerance": float(tolerance), "same_action": True}
    if not result["passed"]:
        raise SnapshotReplayError(f"restore same-action next-state error {error} > {tolerance}")
    return result


@dataclass
class CandidateOutcome:
    candidate_id: int
    candidate_seed: int
    actions: np.ndarray
    poses: np.ndarray
    success: bool
    policy_forwards: int
    environment_steps: int
    snapshot: StageRSnapshot | None = None


def _factory_call(factory: Callable[..., Any], task_id: int, init_state: int, candidate_id: int, seed: int, variant: Any) -> Any:
    try:
        return factory(task_id=task_id, init_state=init_state, candidate_id=candidate_id, seed=seed, variant=variant)
    except TypeError:
        try:
            return factory(task_id, init_state, candidate_id, seed, variant)
        except TypeError:
            return factory(task_id, candidate_id, variant)


def collect_family(
    environment_factory: Callable[..., Any],
    policy: Any,
    *,
    task_id: int,
    init_state: int,
    candidate_count: int = MAIN_CANDIDATE_COUNT,
    max_steps: int = 1000,
    variant: Any = None,
    seed_namespace: str = STAGE_S_PROTOCOL_ID,
    validate_snapshots: bool = False,
) -> dict[str, Any]:
    """Collect one complete no-intervention family using real adapters."""

    if candidate_count <= 0 or max_steps <= 0:
        raise ValueError("candidate_count and max_steps must be positive")
    envs = []
    outcomes: list[CandidateOutcome] = []
    try:
        for candidate_id in range(int(candidate_count)):
            seed = stable_seed(seed_namespace, "candidate", task_id, init_state, candidate_id)
            env = _factory_call(environment_factory, task_id, init_state, candidate_id, seed, variant)
            envs.append(env)
            observation = seeded_reset(env, init_state, stable_seed(seed_namespace, "environment", task_id, init_state))
            initial_snapshot = None
            if hasattr(env, "capture_snapshot"):
                initial_snapshot = capture_stage_r_snapshot(env, [], seed, 0, 0, policy=policy)
            queue: list[np.ndarray] = []
            actions: list[np.ndarray] = []
            poses: list[np.ndarray] = []
            forwards = 0
            success = False
            done = False
            for step in range(int(max_steps)):
                if not queue:
                    queue.extend(_sample_chunk(policy, observation, seed, forwards))
                    forwards += 1
                action = np.asarray(queue.pop(0), dtype=np.float32)
                result = _execute_one(env, action)
                observation = _observation(env)
                actions.append(action.copy())
                poses.append(_pose_vector(env, observation))
                success = bool(result.get("success", False))
                done = bool(result.get("done", False))
                if done:
                    break
            if not done:
                raise StageSError(f"family task={task_id} init={init_state} candidate={candidate_id} exceeded max_steps={max_steps}")
            if validate_snapshots and initial_snapshot is not None and actions:
                validate_restore_same_action(env, initial_snapshot, actions[0], policy=policy)
            outcomes.append(CandidateOutcome(candidate_id, seed, np.asarray(actions, dtype=np.float32), np.asarray(poses, dtype=np.float64), success, forwards, len(actions), initial_snapshot))
    finally:
        for env in envs:
            if hasattr(env, "close"):
                env.close()
    family_id = f"task{int(task_id):02d}_init{int(init_state):03d}"
    return {
        "protocol_id": STAGE_S_PROTOCOL_ID,
        "substrate": getattr(variant, "substrate", None) or ("B" if variant is not None else "A_OR_C"),
        "suite": LIBERO_SUITE,
        "task_id": int(task_id),
        "task_name": task_spec(task_id).name,
        "init_state": int(init_state),
        "family_id": family_id,
        "candidate_count": int(candidate_count),
        "outcomes": outcomes,
        "policy_forwards": int(sum(value.policy_forwards for value in outcomes)),
        "environment_steps": int(sum(value.environment_steps for value in outcomes)),
    }


def _snapshot_payload(snapshot: StageRSnapshot | None) -> Any:
    if snapshot is None:
        return None
    return {
        "environment": snapshot.environment,
        "observation_history": snapshot.observation_history,
        "action_queue": snapshot.action_queue,
        "python_rng_state": snapshot.python_rng_state,
        "numpy_rng_state": snapshot.numpy_rng_state,
        "baseline_noise_seed": snapshot.baseline_noise_seed,
        "baseline_noise_counter": snapshot.baseline_noise_counter,
        "step": snapshot.step,
        "policy_rng_state": snapshot.policy_rng_state,
    }


def _pack_family(family: Mapping[str, Any]) -> dict[str, np.ndarray]:
    outcomes: Sequence[CandidateOutcome] = family["outcomes"]
    lengths = np.asarray([len(value.actions) for value in outcomes], dtype=np.int32)
    offsets = np.concatenate(([0], np.cumsum(lengths, dtype=np.int64)))
    pose_width = max((value.poses.shape[1] if value.poses.ndim == 2 else 0) for value in outcomes)
    padded_poses = []
    for value in outcomes:
        poses = value.poses if value.poses.ndim == 2 else np.empty((len(value.actions), 0), dtype=np.float64)
        if poses.shape[1] < pose_width:
            poses = np.pad(poses, ((0, 0), (0, pose_width - poses.shape[1])))
        padded_poses.append(poses)
    return {
        "lengths": lengths,
        "offsets": offsets,
        "actions": np.concatenate([value.actions for value in outcomes], axis=0).astype(np.float32),
        "poses": np.concatenate(padded_poses, axis=0).astype(np.float64),
        "success": np.asarray([value.success for value in outcomes], dtype=np.bool_),
        "candidate_id": np.asarray([value.candidate_id for value in outcomes], dtype=np.int16),
        "candidate_seed": np.asarray([value.candidate_seed for value in outcomes], dtype=np.uint64),
        "generation_step": np.zeros(len(outcomes), dtype=np.int32),
        "policy_forwards": np.asarray([value.policy_forwards for value in outcomes], dtype=np.int32),
        "environment_steps": np.asarray([value.environment_steps for value in outcomes], dtype=np.int32),
    }


def family_is_complete(directory: str | Path, *, expected_candidates: int = MAIN_CANDIDATE_COUNT) -> bool:
    root = Path(directory)
    marker_path = root / "COMPLETED_FAMILY.json"
    sums_path = root / "SHA256SUMS"
    if not marker_path.is_file() or not sums_path.is_file():
        return False
    try:
        marker = json.loads(marker_path.read_text(encoding="utf-8"))
        lines = sums_path.read_text(encoding="utf-8").splitlines()
        for path in (root / "rollouts.npz", root / "genealogy.json", root / "snapshots.pkl", root / "metadata.json"):
            if not path.is_file():
                return False
        expected = {f"{sha256_file(root / name)}  {name}" for name in ("rollouts.npz", "genealogy.json", "snapshots.pkl", "metadata.json")}
        if set(lines) != expected or marker.get("protocol_id") != STAGE_S_PROTOCOL_ID:
            return False
        if marker.get("files") != {name: sha256_file(root / name) for name in ("rollouts.npz", "genealogy.json", "snapshots.pkl", "metadata.json")}:
            return False
        with np.load(root / "rollouts.npz", allow_pickle=False) as data:
            return len(data["success"]) == int(expected_candidates)
    except (OSError, ValueError, KeyError, json.JSONDecodeError):
        return False


def write_family_atomic(directory: str | Path, family: Mapping[str, Any]) -> dict[str, Any]:
    """Persist a family; marker is written last and makes resume fail-closed."""

    root = Path(directory)
    root.mkdir(parents=True, exist_ok=True)
    outcomes: Sequence[CandidateOutcome] = family["outcomes"]
    if len(outcomes) != int(family["candidate_count"]):
        raise ValueError("family candidate count does not match outcomes")
    npz_path = root / "rollouts.npz"
    genealogy = []
    for value in outcomes:
        genealogy.append(
            {
                "candidate_id": int(value.candidate_id),
                "parent_id": None,
                "generation_step": 0,
                "candidate_seed": int(value.candidate_seed),
                "action_prefix": value.actions.astype(float).tolist(),
                "final_success": bool(value.success),
            }
        )
    metadata = {
        "protocol_id": STAGE_S_PROTOCOL_ID,
        "schema_version": 1,
        "substrate": family.get("substrate"),
        "suite": family["suite"],
        "task_id": int(family["task_id"]),
        "task_name": family["task_name"],
        "init_state": int(family["init_state"]),
        "family_id": family["family_id"],
        "candidate_count": int(family["candidate_count"]),
        "policy_forwards": int(family["policy_forwards"]),
        "environment_steps": int(family["environment_steps"]),
        "genealogy_file": "genealogy.json",
        "rollouts_file": "rollouts.npz",
        "snapshots_file": "snapshots.pkl",
        "written_at_unix": time.time(),
    }
    snapshots = {str(value.candidate_id): _snapshot_payload(value.snapshot) for value in outcomes}
    atomic_npz(npz_path, _pack_family(family))
    atomic_json(root / "genealogy.json", genealogy)
    atomic_bytes(root / "snapshots.pkl", pickle.dumps({"schema_version": 1, "candidates": snapshots}, protocol=5))
    atomic_json(root / "metadata.json", metadata)
    names = ("rollouts.npz", "genealogy.json", "snapshots.pkl", "metadata.json")
    hashes = {name: sha256_file(root / name) for name in names}
    atomic_text(root / "SHA256SUMS", "".join(f"{hashes[name]}  {name}\n" for name in names))
    marker = {
        "protocol_id": STAGE_S_PROTOCOL_ID,
        "marker_type": "completed_family",
        "family_id": family["family_id"],
        "candidate_count": int(family["candidate_count"]),
        "files": hashes,
        "checkpoint": "FAMILY_COMPLETE",
    }
    atomic_json(root / "COMPLETED_FAMILY.json", marker)
    return marker


def run_main_screen(
    environment_factory: Callable[..., Any],
    policy: Any,
    output_root: str | Path,
    *,
    substrate: str,
    variant: Any = None,
    initial_states: Sequence[int] = tuple(range(MAIN_INITIAL_STATE_COUNT)),
    task_ids: Sequence[int] = tuple(range(TASK_COUNT)),
    candidate_count: int = MAIN_CANDIDATE_COUNT,
    max_steps: int = 1000,
    validate_snapshots: bool = False,
) -> dict[str, Any]:
    if substrate not in {"A", "B", "C"}:
        raise ValueError("substrate must be A, B, or C")
    completed = skipped = 0
    for task_id in task_ids:
        for init_state in initial_states:
            directory = Path(output_root) / substrate / f"task{int(task_id):02d}" / f"init{int(init_state):03d}"
            if family_is_complete(directory, expected_candidates=candidate_count):
                skipped += 1
                continue
            family = collect_family(
                environment_factory,
                policy,
                task_id=int(task_id),
                init_state=int(init_state),
                candidate_count=int(candidate_count),
                max_steps=int(max_steps),
                variant=variant,
                validate_snapshots=validate_snapshots,
            )
            family["substrate"] = substrate
            write_family_atomic(directory, family)
            completed += 1
    return {"protocol_id": STAGE_S_PROTOCOL_ID, "substrate": substrate, "completed_families": completed, "skipped_complete_families": skipped, "task_count": len(task_ids), "initial_state_count": len(initial_states), "candidate_count": int(candidate_count)}


def calibration_plan(settings: Sequence[Any], *, task_ids: Sequence[int] = CALIBRATION_TASK_IDS, initial_states: Sequence[int] = CALIBRATION_INITIAL_STATES, candidate_count: int = CALIBRATION_CANDIDATE_COUNT) -> dict[str, Any]:
    return {
        "protocol_id": STAGE_S_PROTOCOL_ID,
        "task_ids": [int(value) for value in task_ids],
        "initial_states": [int(value) for value in initial_states],
        "candidate_count": int(candidate_count),
        "settings": list(settings),
        "total_trials_per_setting": int(len(task_ids) * len(initial_states) * candidate_count),
        "persisted_fields_only": ["setting", "successes", "total", "pooled_success"],
        "forbidden_persisted_fields": ["family", "trajectory", "genealogy", "S2", "S3", "S4", "S5", "divergence", "overdispersion", "all_fail"],
    }


def run_pooled_calibration(
    evaluator: Callable[..., bool],
    settings: Sequence[Any],
    *,
    task_ids: Sequence[int] = CALIBRATION_TASK_IDS,
    initial_states: Sequence[int] = CALIBRATION_INITIAL_STATES,
    candidate_count: int = CALIBRATION_CANDIDATE_COUNT,
) -> dict[str, Any]:
    """Run B/C calibration while retaining only aggregate counters."""

    if len(settings) != 4:
        raise ValueError("Stage-S calibration fixes exactly four settings")
    rows = []
    for setting_index, setting in enumerate(settings):
        successes = 0
        total = 0
        for task_id in task_ids:
            for init_state in initial_states:
                for candidate_id in range(int(candidate_count)):
                    seed = stable_seed(STAGE_S_PROTOCOL_ID, "calibration", setting_index, task_id, init_state, candidate_id)
                    successes += int(bool(evaluator(setting, int(task_id), int(init_state), int(candidate_id), int(seed))))
                    total += 1
        rows.append({"setting": setting, "successes": int(successes), "total": int(total), "pooled_success": float(successes / total if total else float("nan"))})
    selected = min(rows, key=lambda row: (abs(float(row["pooled_success"]) - CALIBRATION_TARGET_SUCCESS), str(row["setting"])))
    return {"protocol_id": STAGE_S_PROTOCOL_ID, "target_pooled_success": CALIBRATION_TARGET_SUCCESS, "rows": rows, "selected_setting": selected["setting"]}


def write_pooled_calibration(path: str | Path, result: Mapping[str, Any]) -> dict[str, Any]:
    """Persist only the calibration allow-list; reject accidental leakage."""

    allowed = {"protocol_id", "target_pooled_success", "rows", "selected_setting"}
    if set(result) - allowed:
        raise ValueError(f"calibration result contains forbidden top-level fields: {sorted(set(result) - allowed)}")
    rows = []
    for row in result.get("rows", []):
        if set(row) != {"setting", "successes", "total", "pooled_success"}:
            raise ValueError("calibration row contains non-aggregate fields")
        rows.append({"setting": row["setting"], "successes": int(row["successes"]), "total": int(row["total"]), "pooled_success": float(row["pooled_success"])})
    payload = {"protocol_id": result.get("protocol_id", STAGE_S_PROTOCOL_ID), "target_pooled_success": float(result.get("target_pooled_success", CALIBRATION_TARGET_SUCCESS)), "rows": rows, "selected_setting": result.get("selected_setting")}
    atomic_json(path, payload)
    return payload


def _read_json_candidates(path: Path) -> list[dict[str, Any]]:
    values = []
    for name in ("CHECKPOINT_PROVENANCE.json", "metadata.json", "checkpoint.json", "manifest.json"):
        candidate = path / name if path.is_dir() else path.parent / name
        if not candidate.is_file():
            continue
        try:
            value = json.loads(candidate.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(value, dict):
            values.append(value)
    # The pinned OpenPI PyTorch trainer writes metadata.pt rather than JSON.
    # Loading this small metadata object is needed to prove the exact policy
    # and optimizer step; it is never used to synthesize or alter weights.
    candidate = path / "metadata.pt" if path.is_dir() else path.parent / "metadata.pt"
    if candidate.is_file():
        try:
            import torch

            try:
                value = torch.load(candidate, map_location="cpu", weights_only=False)
            except TypeError:
                value = torch.load(candidate, map_location="cpu")
            if isinstance(value, dict):
                values.append(value)
        except Exception:
            pass
    return values


def _find_step(value: Any) -> int | None:
    if isinstance(value, Mapping):
        for key in ("step", "global_step", "checkpoint_step", "steps"):
            if key in value and isinstance(value[key], (int, float)):
                return int(value[key])
        for child in value.values():
            found = _find_step(child)
            if found is not None:
                return found
    return None


@dataclass(frozen=True)
class CheckpointAudit:
    path: str
    exists: bool
    complete: bool
    exact_policy: bool
    step: int | None
    undertrained: bool
    model_sha256: str | None
    status: str
    errors: tuple[str, ...] = field(default_factory=tuple)

    def as_dict(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "exists": self.exists,
            "complete": self.complete,
            "exact_policy": self.exact_policy,
            "step": self.step,
            "undertrained": self.undertrained,
            "model_sha256": self.model_sha256,
            "status": self.status,
            "errors": list(self.errors),
        }


def audit_undertrained_checkpoint(
    path: str | Path,
    *,
    expected_step: int | None = None,
    hash_model: bool = False,
    require_training_state: bool = False,
) -> CheckpointAudit:
    target = Path(path)
    errors: list[str] = []
    exists = target.exists()
    if not exists:
        return CheckpointAudit(str(target), False, False, False, None, False, None, "MISSING", ("checkpoint path does not exist",))
    model = target / "model.safetensors" if target.is_dir() else target
    if not model.is_file():
        errors.append("missing model.safetensors")
    provenance = _read_json_candidates(target)
    text = " ".join(canonical_json(value).lower() for value in provenance) + " " + str(target).lower()
    exact_policy = "pi05" in text and "libero" in text
    if not exact_policy:
        errors.append("checkpoint is not identified as exact pi05_libero")
    step = _find_step(provenance[0]) if provenance else None
    if step is None:
        match = re.search(r"(?:step|checkpoint)[_-]?(\d+)", str(target), flags=re.IGNORECASE)
        step = int(match.group(1)) if match else None
    if expected_step is not None and step != int(expected_step):
        errors.append(f"step {step!r} != expected {expected_step}")
    if step is None:
        errors.append("checkpoint step is not declared; refusing to infer under-training")
    undertrained = step is not None and step < FULL_PI05_LIBERO_TRAINING_STEPS
    if not undertrained:
        errors.append(f"step {step!r} is not below full training step {FULL_PI05_LIBERO_TRAINING_STEPS}")
    # Real checkpoint completeness requires weights and provenance.  C's
    # training-lineage audit additionally requires the native optimizer and
    # metadata files so a later run can resume full state rather than merely
    # warm-starting model weights.
    complete = model.is_file() and bool(provenance)
    if require_training_state:
        for required in ("optimizer.pt", "metadata.pt"):
            if not target.is_dir() or not (target / required).is_file():
                errors.append(f"missing complete-training-state component: {required}")
        complete = complete and all((target / required).is_file() for required in ("optimizer.pt", "metadata.pt"))
    if not complete:
        errors.append("checkpoint lacks a complete real-weight/provenance pair")
    model_sha = sha256_file(model) if hash_model and model.is_file() else None
    return CheckpointAudit(str(target), True, complete, exact_policy, step, undertrained, model_sha, "PASS" if not errors else "FAIL", tuple(errors))


def audit_undertrained_checkpoint_set(
    paths: Sequence[str | Path],
    *,
    expected_steps: Sequence[int] | None = None,
    hash_model: bool = False,
    require_training_state: bool = False,
) -> dict[str, Any]:
    if len(paths) != UNDERTRAINED_CHECKPOINT_COUNT:
        return {"valid": False, "errors": [f"exactly four real undertrained checkpoints are required, got {len(paths)}"], "checkpoints": []}
    if len({str(Path(path).resolve()) for path in paths}) != len(paths):
        return {"valid": False, "errors": ["checkpoint paths must be unique"], "checkpoints": []}
    effective_steps = tuple(int(value) for value in (C_RETAIN_STEPS if expected_steps is None else expected_steps))
    if effective_steps != tuple(C_RETAIN_STEPS):
        return {
            "valid": False,
            "errors": [f"C checkpoints must be the frozen steps {C_RETAIN_STEPS}, got {effective_steps}"],
            "checkpoints": [],
        }
    audits = [
        audit_undertrained_checkpoint(
            path,
            expected_step=effective_steps[index],
            hash_model=hash_model,
            require_training_state=require_training_state,
        )
        for index, path in enumerate(paths)
    ]
    errors = [f"{audit.path}: {error}" for audit in audits for error in audit.errors]
    return {"valid": not errors, "errors": errors, "checkpoints": [audit.as_dict() for audit in audits], "no_interpolation": True}


def audit_c_checkpoint_schedule(
    checkpoint_root: str | Path,
    *,
    expected_steps: Sequence[int] = C_RETAIN_STEPS,
    require_training_state: bool = True,
) -> dict[str, Any]:
    """Audit the four real C checkpoints that the frozen screen retains."""

    steps = tuple(int(value) for value in expected_steps)
    if steps != tuple(C_RETAIN_STEPS):
        raise CheckpointQualificationError(f"C checkpoint steps are frozen to {C_RETAIN_STEPS}, got {steps}")
    root = Path(checkpoint_root)
    paths = [root / str(step) for step in steps]
    result = audit_undertrained_checkpoint_set(
        paths,
        expected_steps=steps,
        require_training_state=require_training_state,
    )
    result.update(
        {
            "checkpoint_root": str(root.resolve()),
            "expected_steps": list(steps),
            "full_reference_step": C_FULL_REFERENCE_STEP,
            "label": "WEAK_SUBSTRATE",
        }
    )
    return result


def build_c_training_launcher_contract(
    *,
    qpilots_root: str | Path,
    output_root: str | Path,
    checkpoint_paths: Sequence[str | Path],
    expected_steps: Sequence[int] | None = None,
    python: str = "python",
    gpu_count: int = PAI_MAX_GPU,
    resource_pool: str = "idle",
    seed: int = C_TRAINING_SEED,
    num_train_steps: int = C_TRAINING_STEPS,
    save_interval: int = C_SAVE_INTERVAL,
    base_checkpoint: str | Path | None = None,
) -> dict[str, Any]:
    """Return a real OpenPI PyTorch training command; never synthesize C."""

    if int(seed) != C_TRAINING_SEED:
        raise CheckpointQualificationError(f"C training seed is frozen to {C_TRAINING_SEED}, got {seed}")
    if int(num_train_steps) != C_TRAINING_STEPS:
        raise CheckpointQualificationError(f"C training steps are frozen to {C_TRAINING_STEPS}, got {num_train_steps}")
    if int(save_interval) != C_SAVE_INTERVAL:
        raise CheckpointQualificationError(f"C save interval is frozen to {C_SAVE_INTERVAL}, got {save_interval}")
    if int(gpu_count) != PAI_MAX_GPU:
        raise CheckpointQualificationError(f"C production launcher requires {PAI_MAX_GPU} GPUs, got {gpu_count}")
    if resource_pool not in {"idle", "robot_idle"}:
        raise CheckpointQualificationError(f"C launcher supports the idle robot pool only, got {resource_pool!r}")
    steps = tuple(int(value) for value in (C_RETAIN_STEPS if expected_steps is None else expected_steps))
    if steps != tuple(C_RETAIN_STEPS):
        raise CheckpointQualificationError(f"C checkpoint steps are frozen to {C_RETAIN_STEPS}, got {steps}")
    audit = audit_undertrained_checkpoint_set(
        checkpoint_paths,
        expected_steps=steps,
        require_training_state=True,
    )
    openpi = Path(qpilots_root) / "third_party" / "openpi"
    output_base = Path(output_root).resolve()
    experiment_name = "r142_stage_s_c_undertrained_seed42"
    checkpoint_dir = output_base / "pi05_libero" / experiment_name
    command = [
        "torchrun",
        "--standalone",
        "--nnodes=1",
        f"--nproc_per_node={PAI_MAX_GPU}",
        str(openpi / "scripts" / "train_pytorch.py"),
        "pi05_libero",
        "--exp_name",
        experiment_name,
        "--checkpoint_base_dir",
        str(output_base),
        "--save_interval",
        str(C_SAVE_INTERVAL),
        "--num_train_steps",
        str(C_TRAINING_STEPS),
        "--seed",
        str(C_TRAINING_SEED),
        "--keep_period",
        str(C_SAVE_INTERVAL),
    ]
    if base_checkpoint is not None:
        command.extend(["--pytorch_weight_path", str(Path(base_checkpoint).resolve())])
    resume_command = list(command) + ["--resume"]
    base_checkpoint_value = str(Path(base_checkpoint).resolve()) if base_checkpoint is not None else None
    base_checkpoint_ready = bool(
        base_checkpoint_value
        and Path(base_checkpoint_value).is_dir()
        and (Path(base_checkpoint_value) / "model.safetensors").is_file()
    )
    return {
        "protocol_id": STAGE_S_PROTOCOL_ID,
        "substrate": "C",
        "label": "WEAK_SUBSTRATE",
        "same_policy": "pi05_libero",
        "audit": audit,
        "launcher": {
            "working_directory": str(openpi.resolve()),
            "python": str(python),
            "command": command,
            "shell": "cd " + str(openpi.resolve()) + " && " + " ".join(command),
            "resume_command": resume_command,
            "resume_shell": "cd " + str(openpi.resolve()) + " && " + " ".join(resume_command),
            "gpu_count": PAI_MAX_GPU,
            "cpu_cores": PAI_MAX_CPU,
            "memory_gib": PAI_MAX_MEMORY_GIB,
            "resource_pool": resource_pool,
            "no_pai_submit_performed": True,
            "requires_external_base_checkpoint": not base_checkpoint_ready,
        },
        "training_contract": {
            "seed": C_TRAINING_SEED,
            "num_train_steps": C_TRAINING_STEPS,
            "save_interval_steps": C_SAVE_INTERVAL,
            "retain_and_audit_steps": list(C_RETAIN_STEPS),
            "full_reference_step": C_FULL_REFERENCE_STEP,
            "checkpoint_base_dir": str(output_base),
            "checkpoint_dir": str(checkpoint_dir),
            "base_checkpoint": base_checkpoint_value,
            "base_checkpoint_ready": base_checkpoint_ready,
            "resume": "discover_newest_complete_same_run_lineage",
            "full_state_required": True,
            "post_save_retention_hook": "external_fail_closed_controller_required",
            "ready_for_training": False,
        },
        "checkpoint_contract": {
            "count": UNDERTRAINED_CHECKPOINT_COUNT,
            "paths": [str(Path(path).resolve()) for path in checkpoint_paths],
            "expected_steps": list(steps),
            "interpolation": False,
            "artificial_degradation": False,
        },
    }


STAGE_S_NO_JOB_WINDOWS = (
    {"start": "09:30", "end": "09:40", "timezone": "Asia/Shanghai"},
    {"start": "19:30", "end": "19:40", "timezone": "Asia/Shanghai"},
)


def build_pai_stage_s_payload(
    *,
    run_id: str,
    output_root: str | Path,
    log_root: str | Path,
    command: Sequence[str] | None = None,
    working_directory: str | Path | None = None,
    c_contract: Mapping[str, Any] | None = None,
    resource_pool: str = "idle",
    gpu_count: int = PAI_MAX_GPU,
    cpu_cores: int = PAI_MAX_CPU,
    memory_gib: int = PAI_MAX_MEMORY_GIB,
    shared_memory_gib: int = PAI_MAX_MEMORY_GIB,
) -> dict[str, Any]:
    """Build a fail-closed, non-submitting idle-PAI payload.

    The payload describes the exact control-plane contract, persistent resume
    paths, and the two daily Beijing no-job windows.  It intentionally does
    not call DLC/PAI; a separate authorized orchestrator must validate and
    submit it after external credentials and mount readback are available.
    """

    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]{2,127}", str(run_id)):
        raise ValueError(f"invalid run_id {run_id!r}")
    if resource_pool not in {"idle", "robot_idle"}:
        raise ValueError(f"Stage-S payload supports robot idle only, got {resource_pool!r}")
    if (int(gpu_count), int(cpu_cores), int(memory_gib), int(shared_memory_gib)) != (
        PAI_MAX_GPU,
        PAI_MAX_CPU,
        PAI_MAX_MEMORY_GIB,
        PAI_MAX_MEMORY_GIB,
    ):
        raise ValueError("Stage-S production payload is frozen to 8 GPU / 88 CPU / 1525 GiB")
    output = Path(output_root).resolve()
    logs = Path(log_root).resolve()
    for name, path in (("output_root", output), ("log_root", logs)):
        if not path.is_absolute():
            raise ValueError(f"{name} must be absolute")
        if not str(path).startswith("/mnt/cpfs/zbl-cpfs-new/"):
            raise ValueError(f"{name} must use the new /mnt/cpfs/zbl-cpfs-new storage namespace")
    if c_contract is not None:
        contract_command = c_contract.get("launcher", {}).get("command") if isinstance(c_contract.get("launcher"), Mapping) else None
        if command is None and contract_command:
            command = [str(value) for value in contract_command]
        if working_directory is None and isinstance(c_contract.get("launcher"), Mapping):
            working_directory = c_contract["launcher"].get("working_directory")
    if command is None:
        raise ValueError("a real foreground command or C launcher contract is required")
    command_values = [str(value) for value in command]
    if not command_values or any(not value for value in command_values):
        raise ValueError("foreground command must be non-empty")
    command_text = " ".join(command_values)
    if "sleep" in command_text or "|| true" in command_text:
        raise ValueError("payload cannot hide failures with sleep or || true")
    for legacy in ("/mnt/cpfs/leon", "/workspace/leon"):
        if legacy in command_text or legacy in str(working_directory or ""):
            raise ValueError(f"payload contains legacy storage prefix {legacy}")
    workdir = str(Path(working_directory).resolve()) if working_directory is not None else str(output)
    checkpoint_root = output / "pi05_libero" / "r142_stage_s_c_undertrained_seed42"
    checkpoint_contract = {
        "save_interval_steps": C_SAVE_INTERVAL,
        "retain_and_audit_steps": list(C_RETAIN_STEPS),
        "full_reference_step": C_FULL_REFERENCE_STEP,
        "full_state_resume": True,
        "startup_repair": True,
        "post_save_failure_fatal": True,
    }
    if c_contract is not None and isinstance(c_contract.get("training_contract"), Mapping):
        declared_steps = tuple(
            int(value)
            for value in c_contract["training_contract"].get("retain_and_audit_steps", C_RETAIN_STEPS)
        )
        declared_interval = int(
            c_contract["training_contract"].get("save_interval_steps", C_SAVE_INTERVAL)
        )
        declared_reference = int(
            c_contract["training_contract"].get("full_reference_step", C_FULL_REFERENCE_STEP)
        )
        if declared_steps != tuple(C_RETAIN_STEPS):
            raise ValueError(f"PAI payload checkpoint steps are frozen to {C_RETAIN_STEPS}, got {declared_steps}")
        if declared_interval != C_SAVE_INTERVAL or declared_reference != C_FULL_REFERENCE_STEP:
            raise ValueError("PAI payload checkpoint schedule does not match the frozen C contract")
        checkpoint_contract.update(
            {
                "save_interval_steps": declared_interval,
                "retain_and_audit_steps": list(declared_steps),
                "full_reference_step": declared_reference,
            }
        )
    payload = {
        "schema": "r142-stage-s-pai-payload-v1",
        "protocol_id": STAGE_S_PROTOCOL_ID,
        "run_id": str(run_id),
        "substrate": "C",
        "label": "WEAK_SUBSTRATE",
        "no_pai_submit_performed": True,
        "ready_for_submission": False,
        "foreground_command": command_values,
        "command": command_values,
        "working_directory": workdir,
        "resource": {
            "resource_pool": str(resource_pool),
            "pool_family": "robot",
            "resource_alias": PAI_ROBOT_IDLE_RESOURCE_ALIAS,
            "resource_id": PAI_ROBOT_IDLE_RESOURCE_ID,
            "quota_name": PAI_ROBOT_IDLE_QUOTA_NAME,
            "oversold_type": "AcceptQuotaOverSold",
            "worker": 1,
            "gpu": PAI_MAX_GPU,
            "gpu_count": PAI_MAX_GPU,
            "cpu": PAI_MAX_CPU,
            "cpu_cores": PAI_MAX_CPU,
            "memory_gib": PAI_MAX_MEMORY_GIB,
            "shared_memory_gib": PAI_MAX_MEMORY_GIB,
            "disable_ecs_stock_check": True,
        },
        "fault_tolerance": {
            "execution_mode": "Sync",
            "policy": "OnFailure",
            "max_num_of_job_restart": 50,
            "launcher_attempts_per_incarnation": 1,
            "persistent_application_autoresume": True,
        },
        "persistence": {
            "checkpoint_root": str(checkpoint_root),
            "requested_output_root": str(output),
            "log_root": str(logs),
            "resume": "discover_newest_complete_same_run_lineage",
            "same_run_id_on_resume": True,
            "full_optimizer_scheduler_rng_state": True,
        },
        "checkpoint_contract": checkpoint_contract,
        "daily_no_job_windows": [dict(window) for window in STAGE_S_NO_JOB_WINDOWS],
        "no_job_window_policy": {
            "timezone": "Asia/Shanghai",
            "stop_before": ["09:30", "19:30"],
            "resume_after": ["09:40", "19:40"],
            "fail_closed": True,
        },
        "identity": {"runtime_uid": 2254, "runtime_gid": 2254, "ownership_probe_required": True},
        "fail_closed": True,
    }
    return payload


def write_pai_stage_s_payload(path: str | Path, payload: Mapping[str, Any]) -> dict[str, Any]:
    """Atomically write a previously validated Stage-S PAI payload."""

    if payload.get("no_pai_submit_performed") is not True or payload.get("fail_closed") is not True:
        raise ValueError("payload must be explicitly non-submitting and fail-closed")
    atomic_json(path, dict(payload))
    return dict(payload)


def import_callback(spec: str) -> Callable[..., Any]:
    """Load ``module:function`` for the real-runtime scripts."""

    if ":" not in spec:
        raise ValueError("callback must have module:function form")
    module, function = spec.split(":", 1)
    value = getattr(importlib.import_module(module), function)
    if not callable(value):
        raise TypeError(f"callback {spec} is not callable")
    return value


__all__ = [
    "B_INIT_STATE_COUNT",
    "B_INIT_STATE_SEED_BASE",
    "BVariant",
    "CALIBRATION_CANDIDATE_COUNT",
    "CALIBRATION_INITIAL_STATES",
    "CALIBRATION_TASK_IDS",
    "CandidateOutcome",
    "C_FULL_REFERENCE_STEP",
    "C_RETAIN_STEPS",
    "C_SAVE_INTERVAL",
    "C_TRAINING_SEED",
    "C_TRAINING_STEPS",
    "CheckpointAudit",
    "CheckpointQualificationError",
    "LIBERO_10_TASK_NAMES",
    "LIBERO_TASK_SPECS",
    "MAIN_CANDIDATE_COUNT",
    "MAIN_INITIAL_STATE_COUNT",
    "MissingRegeneratedInitialStates",
    "PAI_MAX_CPU",
    "PAI_MAX_GPU",
    "PAI_MAX_MEMORY_GIB",
    "PROXIMITY_MAGNITUDES",
    "SNAPSHOT_REPLAY_TOLERANCE",
    "STAGE_S_NO_JOB_WINDOWS",
    "STAGE_S_PROTOCOL_ID",
    "StageRPolicyAdapter",
    "StageRSnapshot",
    "audit_c_checkpoint_schedule",
    "audit_undertrained_checkpoint",
    "audit_undertrained_checkpoint_set",
    "b_init_state_seed",
    "build_b_variant_suite",
    "build_b_variant_matrix",
    "build_c_training_launcher_contract",
    "build_pai_stage_s_payload",
    "calibration_plan",
    "capture_stage_r_snapshot",
    "collect_family",
    "family_is_complete",
    "generate_b_variant",
    "generate_variant_initial_qpos",
    "import_callback",
    "make_libero_qpos_simulator_factory",
    "make_stage_r_policy_factory",
    "make_stage_r_task64_factory",
    "run_main_screen",
    "run_pooled_calibration",
    "seeded_reset",
    "stable_seed",
    "validate_regenerated_initial_states",
    "validate_restore_same_action",
    "write_b_variant",
    "write_family_atomic",
    "write_pai_stage_s_payload",
    "write_pooled_calibration",
    "_execute_one",
    "_observation",
    "_pose_vector",
    "_sample_chunk",
    "_state_vector",
]
